# ============================================================
#  ProyectoBancario — Backend Spring Boot
# ============================================================

# Servidor
server.port=8080

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=BancoSecretKey2025SuperSeguraParaFirmarTokens123!
app.jwt.expiration-ms=86400000

# Uploads
app.uploads.fotos=uploads/fotos
